# -*- coding: utf-8 -*-
"""CIFAR10PyTorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15FWnqj0UYk37BaEz4c1loCQ8u1rBEJcm

# Packages and Libararies
"""

import torch
from torch import nn

import torchvision
from torchvision import datasets, transforms,  models
from torchvision.transforms import ToTensor
from torch.utils.data import Dataset, DataLoader


import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sn
from sklearn.metrics import confusion_matrix

from tqdm.auto import tqdm
import requests
from pathlib import Path
from timeit import default_timer as timer
import random

print(torch.__version__)
print(torchvision.__version__)

def print_train_time( start: int,
                      end: int,
                      device: torch.device = None):
    total_time = end - start
    print(f'train time on {device}: {total_time:.2f} seconds')
    return total_time


start_time = timer()
###
###
end_time = timer()

print_train_time(start = start_time, end = end_time, device = 'cpu')

device = "cuda" if torch.cuda.is_available() else "cpu"
device

"""# Data Preparation

## Data Extraction
"""

train_set = datasets.CIFAR10(
    root= "/content/drive/MyDrive/Datasets/CIFAR10",
    train = True ,
    transform = ToTensor(),
    target_transform = None ,
    download = False

)

test_set = datasets.CIFAR10(
    root = "/content/drive/MyDrive/Datasets/CIFAR10",
    train = False,
    transform = ToTensor(),
    target_transform = None,
    download = False

)

"""## Train-set and Test-set Investigation"""

len(train_set), len(test_set)

print(f'{train_set}\n')
print('===========================')
print(f'{train_set[0]}\n')
print('===========================')
print(f'image: {train_set[0][0]}\n')
print('===========================')
print(f'label: {train_set[0][1]}')

idx = torch.randint(0, len(train_set), size = ())
image, label = train_set[idx]

print(f'label: {label}')
print(f'Image: {image}')
print(f'Image Shape: {image.shape}')

class_names = train_set.classes
class_to_idx = train_set.class_to_idx
targets = train_set.targets

print(class_names)
print(class_to_idx)
print(targets)

"""## Visualize Images and Labels"""

print(image.shape)    # -> working with torch
print(image.permute(1,2,0).numpy().shape)   # working with -> matplit

img_np = image.permute(1, 2, 0).numpy()
plt.imshow(img_np)
plt.title(class_names[label])
plt.axis(False)

def plot_images_from_dataset(data, class_names):
    plt.subplots(nrows =4, ncols =4, figsize=(10 , 8))
    for i in range(0, 4*4):
        num = torch.randint(0, len(data), size = ())
        image_sample, label_sample = data[num]
        permuted_image_sample = image_sample.permute(1,2,0).numpy()
        plt.subplot(4,4,i+1)
        plt.imshow(permuted_image_sample)
        plt.title(class_names[label_sample])
        plt.axis(False)

plot_images_from_dataset(data = train_set, class_names = class_names)

"""## Batching the Dataset"""

train_loader = DataLoader(dataset = train_set,
                          batch_size  = 32,
                          shuffle = True)

test_loader = DataLoader(dataset= test_set,
                         batch_size = 32,
                         shuffle = False)

print(f'Train-loader length: {len(train_loader)}, Test-loader length: {len(test_loader)}')

train_feature_batch, train_label_batch = next(iter(train_loader))
print('Feature-batch_shape: ', train_feature_batch.shape)
print('Label-batch-shape: ', train_label_batch.shape)

"""## Visualize Samples from Batches"""

def plot_sample_from_batch(data, class_names):

    batch_of_images, batch_of_labels = next(iter(data))
    rand_num = torch.randint(0 , len(batch_of_images), size = ())
    image_sample, label_sample = batch_of_images[rand_num], batch_of_labels[rand_num]
    permuted_image_sample = image_sample.permute(1,2,0).numpy()
    plt.imshow(permuted_image_sample)
    plt.title(class_names[label_sample])
    plt.axis(False)

plot_sample_from_batch(data = train_loader, class_names = class_names )

"""## Data Processing with `nn.layers`"""

train_image_batch , train_label_batch = next(iter(train_loader))
x = train_image_batch[0]
flatten_model = nn.Flatten()
output = flatten_model(x)

print(f'{x.shape} -> {output.shape}')

"""# Model0 Base-Line

## Create the Model
"""

class CIFAR10ModelV0(nn.Module):
    def __init__(self, input_shape: int, hidden_units: int, output_shape: int):
        super().__init__()

        self.layer_stack = nn.Sequential(
            nn.Flatten(),
            nn.Linear(in_features= input_shape,
                      out_features= hidden_units),
            nn.Linear(in_features= hidden_units,
                      out_features= output_shape)
        )

    def forward(self, x):
        return self.layer_stack(x)

model_0 = CIFAR10ModelV0(input_shape = 3*32*32,
                          hidden_units = 10,
                          output_shape=(len(class_names))).to(device)
print(model_0)

"""## Investigate the Model"""

# Make prediction with untrained model
torch.random.manual_seed(42)
dummy = torch.rand([1,3,32,32]).to(device)  # a random image from the batch
pred = model_0(dummy)
print('Pred-Probs:', pred)  # predicted probabilities
print('Pred-Labels:', torch.argmax(pred, dim = 1)) # predicted labels

# Model Weights
model_0.state_dict()

"""## Loss Function, Optimizer and Accuracy Function"""

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(params = model_0.parameters(),
                            lr = 0.001)

# Calculate accuracy (a classification metric)
def accuracy_fn(y_true, y_pred):
    """Calculates accuracy between truth labels and predictions.

    Args:
        y_true (torch.Tensor): Truth labels for predictions.
        y_pred (torch.Tensor): Predictions to be compared to predictions.

    Returns:
        [torch.float]: Accuracy value between y_true and y_pred, e.g. 78.45
    """
    correct = torch.eq(y_true, y_pred).sum().item()
    acc = (correct / len(y_pred)) * 100
    return acc

"""## Train the model"""

# Set the seed
torch.manual_seed(42)
# Start training time
start_train_on_gpu = timer()

batchs  = 15
# Training and Testing loop
for batch in tqdm(range(batchs)):
    print(f'Epoch: {batch}\n------')

    ###TRAINING LOOP
    train_loss = 0
    #Loop through the trainig batches
    for batch, (X, y) in enumerate(train_loader):
        # 0. Push tensors to GPU
        X, y = X.to(device), y.to(device)

        model_0.train()
        # 1. Pass forward
        y_pred = model_0(X)
        # 2. Calculate loss per batch
        loss = loss_fn(y_pred, y)
        train_loss += loss.item() # Accumelate the loss value in batches
        # 3. Set optimizer grad to zero
        optimizer.zero_grad()
        # 4. Loss backward
        loss.backward()
        # 5. Taking steps with optimizer (update the parameters per epoch)
        optimizer.step()

        if batch % 400 == 0:
            print(f'Looked at {batch * len(X)} / {len(train_loader.dataset)} samples')
    # Calculate train loss average per batch
    train_loss /= len(train_loader)

    ###Tesing
    test_loss, test_acc = 0, 0
    model_0.eval()
    with torch.inference_mode():
        for X_test, y_test in test_loader:
            X_test, y_test = X_test.to(device), y_test.to(device)
            # 1. Forward pass
            y_pred_test = model_0(X_test)
            # 2. Calculate Loss (accumately)
            test_loss += loss_fn(y_pred_test, y_test).item()
            # 3. Caculate accuracy (accumately)
            test_acc += accuracy_fn(
                y_true = y_test,
                y_pred = y_pred_test.argmax(dim = 1)
            )
        #Test Loss average per epoch
        test_loss /=  len(test_loader)
        #Test accuracy average per epoch
        test_acc /= len(test_loader)

    print(f'Train loss: {train_loss:.4f} | Test loss: {test_loss:.4f} | Test Acc: {test_acc:.2f}%')

stop_train_on_gpu = timer()

total_train_time_model_0 = print_train_time(start = start_train_on_gpu,
                                            end= stop_train_on_gpu,
                                            device = str(next(model_0.parameters()).device))

# Evaluate the model on the test-set
def model_eval(model: torch.nn.Module,
               data_loader: torch.utils.data.DataLoader,
               loss_fn: torch.nn.Module,
               accuracy_fn: torch.nn.Module,
               device = None):
    total_loss, total_acc = 0, 0
    model.eval()
    with torch.inference_mode():
        for X, y in data_loader:
            X, y = X.to(device), y.to(device)

            y_pred = model(X)

            batch_loss = loss_fn(y_pred,y).item()
            total_loss += batch_loss
            acc = accuracy_fn(y_true = y,
                              y_pred = y_pred.argmax(dim = 1))
            total_acc += acc

        total_loss /= len(data_loader)
        total_acc /= len(data_loader)


    return {"model_name": model.__class__.__name__,
        "model_loss": total_loss,
        "model_acc": total_acc
        }

model_0_results = model_eval(model = model_0,
                             data_loader = test_loader,
                             loss_fn = loss_fn,
                             accuracy_fn = accuracy_fn,
                             device = device)

model_0_results

"""# Model1 Non-Linearity

## Create the Model
"""

class ModelCIFAR10V1(nn.Module):
    def __init__(self,input_shape, hidden_units, output_shape):
        super().__init__()

        self.stacked_layers = nn.Sequential(
            nn.Flatten(),
            nn.Linear(in_features=input_shape,
                      out_features=hidden_units),
            nn.ReLU(),
            nn.Linear(in_features=hidden_units,
                      out_features = output_shape),
            nn.ReLU()
        )

    def forward(self, x: torch.Tensor):
        return self.stacked_layers( x)

model_1 = ModelCIFAR10V1(input_shape= 3*32*32 ,
                         hidden_units = 30,
                         output_shape=10).to(device)
model_1

"""## Loss Function and Optimizer"""

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(params = model_1.parameters(),
                            lr = 0.001)

"""## Train the Model"""

def Train_step(model: nn.Module,
               data_loader,
               loss_fn,
               optimizer,
               accuracy_fn,
               device):

    train_loss, train_acc = 0, 0
    for batch, (X, y) in enumerate(data_loader):
        X, y = X.to(device), y.to(device)

        model.train()

        y_pred = model(X)

        loss = loss_fn(y_pred, y)
        train_loss += loss.item()

        accuracy = accuracy_fn(y_true = y,
                               y_pred = y_pred.argmax(dim = 1))
        train_acc += accuracy

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if batch % 400 == 0:
            print(f'Looked at {batch * len(X)} / {len(train_loader.dataset)} samples')

    train_loss /= len(data_loader)
    train_acc /= len(data_loader)
    print(f'Train Loss: {train_loss:.4f} | Train Accuracy: {train_acc:.2f}%')

def Test_step(model,
              data_loader,
              loss_fn,
              accuracy_fn,
              device):
    test_loss, test_acc = 0, 0
    model.eval()
    with torch.inference_mode():
        for X_test, y_test in data_loader:

            X_test, y_test = X_test.to(device), y_test.to(device)

            y_pred = model(X_test)

            loss = loss_fn(y_pred, y_test)
            test_loss += loss.item()

            accuracy = accuracy_fn(y_true = y_test,
                                   y_pred = y_pred.argmax(dim = 1))
            test_acc += accuracy


        test_loss/=len(data_loader)
        test_acc/=len(data_loader)
        print(f'Test Loss: {test_loss:.4f} | Test_accuracy: {test_acc:.2f}%')

start_train_on_gpu = timer()

epochs = 30
for epoch in tqdm(range(epochs)):
    print(f'Epochs: {epoch}\n-------')

    Train_step(model_1,
               train_loader,
               loss_fn,
               optimizer,
               accuracy_fn ,
               device)

    Test_step(model_1,
              test_loader,
              loss_fn,
              accuracy_fn,
              device)

stop_train_on_gpu = timer()

total_train_time_model_1 = print_train_time(start= start_train_on_gpu,
                 end = stop_train_on_gpu,
                device = str(next(model_1.parameters()).device))

def model_eval(model,
               data_loader,
               loss_fn,
               accuracy_fn,
               device):

    total_loss, total_acc = 0, 0
    model.eval()
    with torch.inference_mode():
        for X, y in data_loader:
            X, y = X.to(device), y.to(device)
            y_pred = model(X)
            batch_loss = loss_fn(y_pred , y )
            total_loss += batch_loss.item()
            batch_acc = accuracy_fn(y_true = y,
                              y_pred = y_pred.argmax(dim =1))
            total_acc += batch_acc

        total_loss /= len(data_loader)
        total_acc /= len(data_loader)

    return {'model_name': model.__class__.__name__,
            'model_loss': total_loss,
            'model_acc': total_acc}

model_1_results = model_eval(model = model_1 ,
                             data_loader = test_loader ,
                             loss_fn = loss_fn ,
                             accuracy_fn=accuracy_fn,
                             device = device)

model_1_results

"""# Model2 Convnet

## Create the model
"""

class ModelCIFAR10V2(nn.Module):
    def __init__(self, input_shape=3, hidden_units=32, output_shape=10):
        super().__init__()

        self.block_1 = nn.Sequential(
            nn.Conv2d(input_shape, hidden_units, 3, padding=1, bias=False),
            nn.BatchNorm2d(hidden_units),
            nn.ReLU(),
            nn.Conv2d(hidden_units, hidden_units, 3, padding=1, bias=False),
            nn.BatchNorm2d(hidden_units),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.block_2 = nn.Sequential(
            nn.Conv2d(hidden_units, hidden_units*2, 3, padding=1, bias=False),
            nn.BatchNorm2d(hidden_units*2),
            nn.ReLU(),
            nn.Conv2d(hidden_units*2, hidden_units*2, 3, padding=1, bias=False),
            nn.BatchNorm2d(hidden_units*2),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.block_3 = nn.Sequential(
            nn.Conv2d(hidden_units*2, hidden_units*4, 3, padding=1, bias=False),
            nn.BatchNorm2d(hidden_units*4),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Dropout(0.5),  # Dropout before linear
            nn.Linear(hidden_units*4 * 4 * 4, output_shape)
        )

    def forward(self, x):
        x = self.block_1(x)
        x = self.block_2(x)
        x = self.block_3(x)
        x = self.classifier(x)
        return x

model_2 = ModelCIFAR10V2(input_shape = 3,
                         hidden_units = 32,
                         output_shape = 10).to(device)

model_2

"""## Loss Function and Optimizer"""

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(params = model_2.parameters(),
                             lr = 0.001)

"""## Train the model"""

def train_step(model: torch.nn.Module,
               data_loader: torch.utils.data.DataLoader,
               optimizer,#: torch.optim.optimizer,
               loss_fn: torch.nn.Module,
               accuracy_fn,
                 device):
    train_loss, train_acc = 0, 0
    for batch, (X_train, y_train) in enumerate(data_loader):

        X_train, y_train = X_train.to(device), y_train.to(device)
        model.train()

        y_pred = model(X_train)

        loss = loss_fn(y_pred, y_train)
        train_loss += loss.item()

        acc = accuracy_fn(y_true =y_train,
                          y_pred = y_pred.argmax(dim = 1))
        train_acc += acc

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if batch % 400 == 0:
            print(f'Looked at {batch * len(X_train)} / {len(data_loader)} samples')

    train_loss /= len(data_loader)
    train_acc /= len(data_loader)
    print(f'Train Loss: {train_loss:.4f} | Train accuracy: {train_acc:.2f}%')


def test_step(model: torch.nn.Module,
              data_loader: torch.utils.data.DataLoader,
              loss_fn: torch.nn.Module,
              accuracy_fn,
              device):
    test_loss, test_acc = 0, 0
    model.eval()
    with torch.inference_mode():
        for X_test, y_test in data_loader:
            X_test, y_test = X_test.to(device), y_test.to(device)
            y_pred = model(X_test)
            loss = loss_fn(y_pred, y_test)
            test_loss += loss.item()
            accuracy = accuracy_fn(y_true = y_test,
                                   y_pred = y_pred.argmax(dim = 1))
            test_acc += accuracy


        test_loss /= len(data_loader)
        test_acc /= len(data_loader)

    print( f'Test Loss:  {test_loss:.4f} | Test Accuracy: {test_acc:.2f}%')

start_trainig_on_gpu = timer()

batches = 20
for batch in tqdm(range(batches)):
    print(f'batch: {batch}\n------')
    train_step(model_2,
               train_loader,
               optimizer,
               loss_fn,
               accuracy_fn,
               device)
    test_step(model_2,
              test_loader,
              loss_fn,
              accuracy_fn,
              device)

stop_training_on_gpu = timer()

total_train_time_model_2 = print_train_time(start = start_trainig_on_gpu,
                                        end = stop_training_on_gpu,
                                            device= device)

# Create a dummy tensor to pass through the convolutional blocks
dummy_tensor = torch.randn(1, 3, 32, 32).to(device) # Batch size, channels, height, width

# Instantiate the model with the corrected input shape
model_2_test = ModelCIFAR10V2(input_shape=3,
                              hidden_units=15,
                              output_shape=10).to(device)

# Pass the dummy tensor through the convolutional blocks
output_of_conv_blocks = model_2_test.block_2(model_2_test.block_1(dummy_tensor))

# Print the shape of the output tensor
print(output_of_conv_blocks.shape)

# Calculate the expected input features for the linear layer
expected_in_features = output_of_conv_blocks.shape[1] * output_of_conv_blocks.shape[2] * output_of_conv_blocks.shape[3]
print(f"Expected in_features for the linear layer: {expected_in_features}")

#Model Evaluation
def eval_model(model,
               data_loader,
               loss_fn,
               accuracy_fn,
               device):

    total_loss, total_acc = 0, 0
    model.eval()
    with torch.inference_mode():
        for X, y in data_loader:

            X, y = X.to(device), y.to(device)

            y_pred = model(X)

            batch_loss = loss_fn(y_pred, y)
            total_loss += batch_loss.item()

            batch_acc = accuracy_fn(y_true = y,
                              y_pred = y_pred.argmax(dim = 1))
            total_acc += batch_acc


        total_loss /= len(data_loader)
        total_acc /= len(data_loader)

    return {'model_name':model.__class__.__name__,
            'model_loss': total_loss,
            'model_acc': total_acc}

model_2_results = eval_model(model_2,
                             test_loader ,
                             loss_fn ,
                             accuracy_fn,
                             device)
model_2_results

"""# Going through CNN Layers

### Conv2d
"""

images  = torch.randn(size = (32, 3, 32,32)) # one batch of 32 numbers of photos
sample_image = images[0]  # one image from that batch
print(images.shape)
print(sample_image.shape)

conv_layer = nn.Conv2d(in_channels = 3 ,
          out_channels = 10,
          kernel_size =3 ,
          stride = 1,
          padding =0 )
conv_layer_output  = conv_layer(sample_image.squeeze())
conv_layer_output.shape

maxpooling_layer = nn.MaxPool2d(kernel_size = 2)
maxpool_output = maxpooling_layer(conv_layer_output)
maxpool_output.shape

"""### MaxPool2d"""

random_tensor = torch.randn(size = (1,1,4,4))
maxpool_output = nn.MaxPool2d(kernel_size = 2)(random_tensor)
maxpool_output.shape



"""# Compare Results"""

compare_results = pd.DataFrame([
    model_0_results,
    model_1_results,
    model_2_results
])

compare_results['training_time'] = [total_train_time_model_0,
                                    total_train_time_model_1,
                                    total_train_time_model_2]
compare_results

compare_results.set_index('model_name')['model_acc'].plot(kind = 'barh', color = 'c')
plt.xlabel('Accuracy%')
plt.ylabel('Model')

"""#Make Prediction with the best Model"""

# Test set investigation
print(test_loader)
print('------')
print(test_set)
print('------')
print('image: ', test_set[0][0])  # First sample image
print('------')
print('label: ', test_set[0][1])  # First sample label
print('------')

img, label = test_set[1] # Seocnd sample
print('image shape: ', img.shape)

# Random data visualization
img_samples = []
label_samples = []

for img, label in random.sample(list(test_set), k = 9):
    img_samples.append(img)
    label_samples.append(label)

print('Image shape: ', img_samples[5].shape)
print('label: ', label_samples[5])

image = img_samples[5].permute(1,2,0).numpy()
label = label_samples[5]
plt.imshow(image)
plt.title(class_names[label])

def make_prediction(model, data):
    pred_probs = []
    model.eval()
    with torch.inference_mode():
        for sample in data:

            # Assuming sample is a list where the first element is the image tensor
            img_tensor = sample[0].to(device)

            pred_logits = model(img_tensor)

            pred_prob = torch.softmax(pred_logits, dim=1)

            pred_probs.append(pred_prob)

    return torch.cat(pred_probs) # Concatenate the predictions

pred_probs = make_prediction(model= model_2,
                             data = test_loader)
print(pred_probs[:10]) # Made prob predictions for first 10 samples

pred_classes = pred_probs.argmax(dim = 1) # Convert predictions to labels
print(pred_classes)

def plot_predictions(data, class_names, pred_classes):
    fig, axes= plt.subplots(nrows = 4, ncols = 4, figsize = (15,12) )
    axes = axes.flatten()

    for (i, sample), axe in zip(enumerate(data), axes):
        img = sample[0]
        img =  img.permute(1,2,0).numpy()
        axe.imshow(img)

        truth_label = class_names[sample[1]]
        pred_label = class_names[pred_classes[i]]

        Text= f'pred:{pred_label} | truth:{truth_label}'

        if truth_label == pred_label:
            axe.set_title(Text, fontsize = 10, c = 'g' )
        else:
            axe.set_title(Text, fontsize = 10, c = 'r' )


    plt.tight_layout()
    plt.show()


plot_predictions(data = test_set,
                 class_names = class_names ,
                 pred_classes = pred_classes )

"""
#Confusion Matrix"""

# Make Prediction
model_pred = []
y_true = []
model_2.eval()
with torch.inference_mode():
    for X,y in tqdm(test_loader):
        X,y = X.to(device),y.to(device)
        y_true.append(y)
        pred_logits = model_2(X)
        pred_label = torch.softmax(pred_logits, dim = 0).argmax(dim = 1)
        model_pred.append(pred_label)


y_pred_tensor = torch.cat(model_pred).to(device)

plt.figure(figsize = (30 , 10))
# Concatenate y_true (list of tensors) into a single tensor and convert to numpy
y_true_tensor = torch.cat(y_true).cpu().numpy()
# y_pred_tensor is already defined as torch.cat(model_pred) in the previous cell, convert it to numpy
y_pred_tensor_np = y_pred_tensor.cpu().numpy()

cf_matrix = confusion_matrix(y_true_tensor, y_pred_tensor_np)
df_cm = pd.DataFrame(cf_matrix / np.sum(cf_matrix, axis=1)[:, None], index = [i for i in class_names],
                     columns = [i for i in class_names])
plt.figure(figsize = (12,7))
sn.heatmap(df_cm, annot=True, cmap ='gist_earth')

